name: dart_scheme
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  big_decimal: ^0.5.0
  path: ^1.9.0
  petitparser: ^7.0.1

dev_dependencies:
  checks: ^0.3.1
  lints: ^6.0.0
  test: ^1.25.6
